### ISSUE TITLE
Please Add Suspicion Agen

### ISSUE THREAD

**Issue by CR-Gjx** [Mars-tin/awesome-theory-of-mind#1]
Hi,

Thanks for your contribution to the research community. Can you check if the paper below matches your interest? Thank you very much!

[Suspicion Agent: Playing Imperfect Information Games with Theory of Mind Aware GPT-4](http://arxiv.org/abs/2309.17277)

[Project Demo](https://huggingface.co/spaces/cr7-gjx/Suspicion-Agent-Demo)  
[Game Data Replay](https://huggingface.co/spaces/cr7-gjx/Suspicion-Agent-Data-Visualization)
[Code](https://github.com/CR-Gjx/Suspicion-Agent)

**Comment by Roihn** [comment]
Hi!

Thanks for introducing your work with us! We have added your paper in section [5.3 Prompting and In-Context Learning for ToM in LLMs](https://github.com/Mars-tin/awesome-theory-of-mind#53-prompting-and-in-context-learning-for-tom-in-llms).

Please feel free to drop comments below if you would like to make any modifications, or you may also pull a request if you prefer.

We will include the links of demo and codes for all the papers in our next update. Thank you for your understanding!
