### ISSUE TITLE
Paper suggestion

### ISSUE THREAD

**Issue by bma-vandijk** [Mars-tin/awesome-theory-of-mind#4]
Hi, I may have one additional paper for your awesome list (thank you very much for compiling it!). Following the possibility for suggestions via opening an issue, here is a link: https://aclanthology.org/2023.conll-1.25/. Thanks, Bram

**Comment by bma-vandijk** [comment]
Some other paper that more generally reflects on the practice of testing (social) cognition with LLMs, is https://aclanthology.org/2023.emnlp-main.779/.  It may be relevant for your repo as well. Thanks, Bram

**Comment by Mars-tin** [comment]
Thank you! We will compile and update in the next version!

**Comment by Flecart** [comment]
As a new maintainer of the list, I added your suggestions @bma-vandijk! Thank you! And happy new year!
