### ISSUE TITLE
Paper suggestions

### ISSUE THREAD

**Issue by KazutoshiShinoda** [Mars-tin/awesome-theory-of-mind#6]
Hi, thank you very much for your hard work! Your awesome list has helped me a lot.

I have two papers that I would like to suggest for inclusion in your awesome list.
These papers propose new ToM benchmarks.

- https://arxiv.org/abs/2402.06044
- https://arxiv.org/abs/2402.15052

**Comment by Flecart** [comment]
Thank you @KazutoshiShinoda for the suggestions! I have added a new section which includes the ACL links!
